name: fossball
dependencies:
    - conda-forge::numpy ~= 1.24.2
    - conda-forge::pandas ~= 2.0.0
    - conda-forge::plotly ~= 5.14.0
    - conda-forge::matplotlib ~= 3.7.1
    - conda-forge::seaborn ~= 0.12.2
    - conda-forge::streamlit ~= 1.9.0
    - conda-forge::openpyxl ~= 3.1.1
